config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :boards
  resources :children
  resources :moms
  resources :dads

  # root to: "dads#index"
  root to: "boards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mom.rb
class Mom < ApplicationRecord
  has_many :children
  has_many :dads, through: :children
end

app/controllers/moms_controller.rb
class MomsController < ApplicationController
  before_action :set_mom, only: [:show, :edit, :update, :destroy]

  # GET /moms
  # GET /moms.json
  def index
    @moms = Mom.all
  end

  # GET /moms/1
  # GET /moms/1.json
  def show
  end

  # GET /moms/new
  def new
    @mom = Mom.new
    @children = Child.where("mom_id IS NULL")
  end

  # GET /moms/1/edit
  def edit
    @children = Child.where("mom_id IS NULL OR mom_id = ?", @mom.id)
  end

  # POST /moms
  # POST /moms.json
  def create
    @mom = Mom.new(mom_params)

    respond_to do |format|
      if @mom.save
        format.html { redirect_to @mom, notice: 'Mom was successfully created.' }
        format.json { render :show, status: :created, location: @mom }
      else
        format.html { render :new }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moms/1
  # PATCH/PUT /moms/1.json
  def update
    respond_to do |format|
      if @mom.update(mom_params)
        format.html { redirect_to @mom, notice: 'Mom was successfully updated.' }
        format.json { render :show, status: :ok, location: @mom }
      else
        format.html { render :edit }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moms/1
  # DELETE /moms/1.json
  def destroy
    @mom.destroy
    respond_to do |format|
      format.html { redirect_to moms_url, notice: 'Mom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mom
      @mom = Mom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mom_params
      params.require(:mom).permit(:name, child_ids: [])
    end
end

app/helpers/moms_helper.rb
module MomsHelper
end

app/views/moms/_form.html.erb
<%= form_with(model: mom, local: true) do |form| %>
  <% if mom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mom.errors.count, "error") %> prohibited this mom from being saved:</h2>

      <ul>
      <% mom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes :child_ids, @children, :id, :name do |b| %>
      <%= b.label { b.check_box + b.text } %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moms/edit.html.erb
<h1>Editing Mom</h1>

<%= render 'form', mom: @mom %>

<%= link_to 'Show', @mom %> |
<%= link_to 'Back', moms_path %>

app/views/moms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moms.each do |mom| %>
      <tr>
        <td><%= mom.name %></td>
        <td><%= link_to 'Show', mom %></td>
        <td><%= link_to 'Edit', edit_mom_path(mom) %></td>
        <td><%= link_to 'Destroy', mom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mom', new_mom_path %> |
<%= link_to 'Home', dads_path %>

app/views/moms/new.html.erb
<h1>New Mom</h1>

<%= render 'form', mom: @mom %>

<%= link_to 'Back', moms_path %>

app/views/moms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mom.name %>
</p>

<% @mom.children.each do |kid| %>
  <div>
    Has a kid <%= kid.name %> from Dad <%= kid.mom ? kid.dad.name : "None" %>
  </div>
<% end %>

<br/>

<%= link_to 'Edit', edit_mom_path(@mom) %> |
<%= link_to 'Back', moms_path %>