config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :boards
  resources :children
  resources :moms
  resources :dads

  # root to: "dads#index"
  root to: "boards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dad.rb
class Dad < ApplicationRecord
  has_many :children
  has_many :moms, through: :children

  accepts_nested_attributes_for :children

  def update_children_attributes(children_attributes)
    children_attributes.each do |_, attrs|
      attrs['dad_id'] = self.id if attrs['dad_id'] == "0"

      if attrs['dad_id'].blank?
        attrs['dad_id'] = nil
        attrs['age'] = nil
      end

      Child.find(attrs['id']).update(attrs.slice(:dad_id, :age))
    end
  end
end

app/controllers/dads_controller.rb
class DadsController < ApplicationController
  before_action :set_dad, only: [:show, :edit, :update, :destroy]

  # GET /dads
  # GET /dads.json
  def index
    @dads = Dad.all
  end

  # GET /dads/1
  # GET /dads/1.json
  def show
  end

  # GET /dads/new
  def new
    @dad = Dad.new
    @children = Child.where("dad_id IS NULL")
  end

  # GET /dads/1/edit
  def edit
    @children = Child.where("dad_id IS NULL OR dad_id = ?", @dad.id)
  end

  # POST /dads
  # POST /dads.json
  def create
    @dad = Dad.new(dad_params)

    respond_to do |format|
      if @dad.save
        @dad.update_children_attributes(dad_child_params['children_attributes'])
        format.html { redirect_to @dad, notice: 'Dad was successfully created.' }
        format.json { render :show, status: :created, location: @dad }
      else
        format.html { render :new }
        format.json { render json: @dad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dads/1
  # PATCH/PUT /dads/1.json
  def update
    respond_to do |format|
      if @dad.update(dad_params)
        @dad.update_children_attributes(dad_child_params['children_attributes'])
        format.html { redirect_to @dad, notice: 'Dad was successfully updated.' }
        format.json { render :show, status: :ok, location: @dad }
      else
        format.html { render :edit }
        format.json { render json: @dad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dads/1
  # DELETE /dads/1.json
  def destroy
    @dad.destroy
    respond_to do |format|
      format.html { redirect_to dads_url, notice: 'Dad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dad
      @dad = Dad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dad_params
      params
        .require(:dad)
        .permit(:name)
    end

    def dad_child_params
      params
        .require(:dad)
        .permit(children_attributes: [:id, :age, :dad_id])
    end
end

app/helpers/dads_helper.rb
module DadsHelper
end

app/views/dads/_form.html.erb
<%= form_with(model: dad, local: true) do |form| %>
  <% if dad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dad.errors.count, "error") %> prohibited this dad from being saved:</h2>

      <ul>
      <% dad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%#= form.collection_check_boxes :child_ids, @children, :id, :name do |b| %>
      <%#= b.label { b.check_box + b.text } %>
    <%# end %>
    <%= form.fields_for :children, @children do |ff| %>
      <div class="field">
        <%= ff.label "name" do %>
          <%= ff.check_box :dad_id, {}, dad.new_record? ? 0 : dad.id, nil %> <%= ff.object.name %>
        <% end %>
      </div>
      <div class="field">
        <%= ff.label :age do %>
          <%= ff.text_field :age %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dads/edit.html.erb
<h1>Editing Dad</h1>

<%= render 'form', dad: @dad %>

<%= link_to 'Show', @dad %> |
<%= link_to 'Back', dads_path %>

app/views/dads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dads.each do |dad| %>
      <tr>
        <td><%= dad.name %></td>
        <td><%= link_to 'Show', dad %></td>
        <td><%= link_to 'Edit', edit_dad_path(dad) %></td>
        <td><%= link_to 'Destroy', dad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dad', new_dad_path %> |
<%= link_to 'Moms', moms_path %> |
<%= link_to 'Kids', children_path %>

app/views/dads/new.html.erb
<h1>New Dad</h1>

<%= render 'form', dad: @dad %>

<%= link_to 'Back', dads_path %>

app/views/dads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dad.name %>
</p>

<% @dad.children.each do |kid| %>
  <div>
    Has a kid <%= kid.name %> from Mom <%= kid.mom ? kid.mom.name : "None" %>
  </div>
<% end %>

<br/>

<%= link_to 'Edit', edit_dad_path(@dad) %> |
<%= link_to 'Back', dads_path %>