config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :boards
  resources :children
  resources :moms
  resources :dads

  # root to: "dads#index"
  root to: "boards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
class Deal < ApplicationRecord
  has_many :board_minutes
  has_many :boards, through: :board_minutes

  accepts_nested_attributes_for :board_minutes,
    reject_if: proc { |attributes| attributes['quantity'].blank? }
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
    Board.find_each { |board| @deal.board_minutes.build(board_id: board.id) }
    @board_minutes = @deal.board_minutes.sort_by(&:board_id)
  end

  # GET /deals/1/edit
  def edit
    Board.unassigned_to_deal(@deal.id).find_each do |board|
      @deal.board_minutes.build(board_id: board.id)
    end

    @board_minutes = @deal.board_minutes.sort_by(&:board_id)
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params
        .require(:deal)
        .permit(
          :name,
          board_minutes_attributes: %i[id quantity board_id]
        )
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_with(model: deal, local: true) do |form| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="board_minutes_table">
    <%= form.fields_for :board_minutes, @board_minutes do |ff| %>
      <div class="row">
        <div class="field">
          <%= ff.object.board.name %>
        </div>
        <div class="field gap-left inline-fields">
          <%= ff.label :quantity %>
          <%= ff.text_field :quantity, class: 'gap-left' %>
        </div>
        <%= ff.hidden_field :board_id %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.name %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %> |
<%= link_to 'Boards', boards_path %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deal.name %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>