config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :boards
  resources :children
  resources :moms
  resources :dads

  # root to: "dads#index"
  root to: "boards#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :board_minutes
  has_many :deals, through: :board_minutes

  scope :unassigned_to_deal,
    ->(deal_id) { where.not(id: Board.joins(:deals).where("deals.id = ?", deal_id)) }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:capacity, :name)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Capacity</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.capacity %></td>
        <td><%= board.name %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %> |
<%= link_to 'Deals', deals_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacity:</strong>
  <%= @board.capacity %>
</p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>